{"uuid": "c7115bad-41fc-452c-89be-398908786be7", "children": ["4866dc0b-73ab-4e5f-87e3-3d877185722a"], "befores": [{"name": "xunit_setup_class_fixture_TestMisAudit", "status": "broken", "statusDetails": {"message": "TypeError: get_web_driver() missing 1 required positional argument: 'url'\n", "trace": "  File \"d:\\pycharm 2019\\pycharmprojects\\uiautotesthmtt\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\pycharm 2019\\pycharmprojects\\uiautotesthmtt\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\pycharm 2019\\pycharmprojects\\uiautotesthmtt\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\pycharm 2019\\pycharmprojects\\uiautotesthmtt\\venv\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\pycharm 2019\\pycharmprojects\\uiautotesthmtt\\venv\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\PyCharm 2019\\PycharmProjects\\uiAutoTestHmtt\\scripts\\test04_mis_audit.py\", line 9, in setup_class\n    driver = GetDriver.get_web_driver()\n"}, "start": 1610016624638, "stop": 1610016624638}], "start": 1610016624638, "stop": 1610016624659}